name: nature-warming-env

channels:
  - default
  - conda-forge

dependencies:
  - python==3.11
  - pandas
  - geopandas
  - openpyxl
  - mkdocs
  - mkdocstrings
  - mkdocstrings-python
